// Babel config is separate from webpack config as Jest cannot understand ES6
// imports, and jest doesn't use the code generated by webpack
module.exports = {
  presets: [['@babel/preset-env', { targets: 'defaults' }]],
};
